### ISSUE TITLE
Login problem with 1.2.0 and TYPO3 7.6.32/7.6.32 Mittwald

### ISSUE THREAD

**Issue by felixrupp** [antwerpes/ap_docchecklogin#15]
Hi there,

I have a problem with the 1.2.0 version of your extension. On our TYPO3 7.6.32/7.6.34 installation, the new version works in first place but does not redirect the user after successful login and so does not authenticate the dummy user. It is not possible to work with the dummy user like that.

Doc Check cream has not been changed and when restoring the 1.1.0 the workflow works again.

Do you have any detail of the internal changes of the extension which might produce this problem?

Thanks and best regards,
Felix

**Comment by Schnoop** [comment]
I think the added strict type comparison is responsible for this failure. I've released a new version 1.2.1. Please check if error still persists.

**Comment by felixrupp** [comment]
@Schnoop Fixes the problem! Thank you for your fast response!
