### ISSUE TITLE
Broken Versions 2.0.0 to 2.2.0 in TER

### ISSUE THREAD

**Issue by felixrupp** [antwerpes/ap_docchecklogin#23]
Hi,

all 2.x.x version of this extension in the TYPO3 Extension Repository are broken because of the following code lines:

https://github.com/antwerpes/ap_docchecklogin/blob/035ead0f28415120e6e8894d5ddfb3d8ac0859b8/Classes/DocCheckAuthenticationService.php#L44

This has to be:
`class DocCheckAuthenticationService extends \TYPO3\CMS\Core\Authentication\AuthenticationService`

https://github.com/antwerpes/ap_docchecklogin/blob/035ead0f28415120e6e8894d5ddfb3d8ac0859b8/Classes/DocCheckAuthenticationService.php#L379

This has to be:
`public function authUser(array $user): int`

Please fix as quick as possible, because this breaks TYPO3 installations in production.

Thanks in advance and kind regards,
Felix

**Comment by lepaff** [comment]
Fixed in 2.2.1
Sorry for the inconvenience.

**Comment by felixrupp** [comment]
@lepaff Thank you!
