### ISSUE TITLE
Typo3 v11 support

### ISSUE THREAD

**Issue by Meeze** [antwerpes/ap_docchecklogin#27]
Hello i was just wondering if typo3 v11 support is planned/coming anytime soon?
i saw the v3 branch in git, so im wondering if maybe itll come with this?

**Comment by Denneee** [comment]
Hello,
yes we are working currently on the update. But at the moment we cant tell a specific timing

**Comment by mdahms** [comment]
Is there any new information about when the update will come?

**Comment by Denneee** [comment]
Die arbeiten an den Update sind für die nächsten 2 Monate eingeplant

**Comment by akmatthies** [comment]
I or we are also looking forward to the update! :)

**Comment by cdominpxp** [comment]
Can you give any estimation, when the update will be available?
Due to the end of LTS Support for Typo3 V10 we need to update the projects to at least Typo3 V11 very soon.

**Comment by Denneee** [comment]
Hello,
we just finaly released our new extension for Typo3 v11: https://github.com/antwerpes/typo3_docchecklogin/

We will not suport the extension ap_docchecklogin anymore.

Further developing will be made in the new repository.
