### ISSUE TITLE
Typo3 7 compatibility

### ISSUE THREAD

**Issue by nkuttler** [antwerpes/ap_docchecklogin#4]
Hi, I was just wondering if the extension should work as is with typo3 version 7+, or if you need support porting it. As it hasn't been updated in a while the compatibility numbers might just be outdated?

**Comment by tpinne** [comment]
I've made a PR #6 if it still of need for you. I also have a fork with some other additions as well https://github.com/tpinne/ap_docchecklogin. But these are changes we needed for our current project. The code/repository itself won't be supported further after our project.

**Comment by jeongil** [comment]
Thanks @tpinne, now merged into master.
