### ISSUE TITLE
TYPO3 8.7 compatibility

### ISSUE THREAD

**Issue by mfell** [antwerpes/ap_docchecklogin#7]
Hi Jochen,
I want to kindly ask, whether there is a chance to get 8.7 compatibility for this extension?
Or: What do you need for sponsoring ... if neccessary.

Greetz from Marc

**Comment by DirkPersky** [comment]
I Uses Typo3 8.7.7 with PHP 7.1 and it basically works.
I only has to fix 2 If Conditions, becouse the Login Response wasn't handled.

In my Pull Request you can see my working Version.
https://github.com/antwerpes/ap_docchecklogin/pull/9

**Comment by w3creative** [comment]
Hi Dirk
Many thanks for this work.
I am unable to make it work. It seems that he does not accept or find the dummy user. It is also true that it is my first experience with Typo3...

I followed your suggestions to modify the script for version 8.7 (I work with 8.7.16). Could it be that this version does not work?

Greetz from Arne

**Comment by DirkPersky** [comment]
Hi,

on ourer 8.7.16 system it still works.
Have you done all of my Changes #9 ?

greetings Dirk

**Comment by w3creative** [comment]
Hi Dirk
I think so… I must say, Typo3 is new for me. Maybe I forgot something.
Anyway, I’m stuck. Maybe, you can help me if I give you some admin access?
Greetz! Arne
[https://htmlsig.com/t/000001BW9729]

Arne Dondeyne / Zaakvoerder
arne@w3-creative.be [arne@w3-creative.be] / +32495374331

w3-creative
www.w3-creative.be [http://www.w3-creative.be]

[https://htmlsig.com/t/000001BYBH3Y]

Success is going from failure to failure without losing enthusiasm.


On za, jul. 14, 2018 at 12:02, Dirk Persky <notifications@github.com> wrote:
Hi,

on ourer 8.7.16 system it still works.
Have you done all of my Changes #9 [https://github.com/antwerpes/ap_docchecklogin/pull/9] ?

greetings Dirk

**Comment by DirkPersky** [comment]
Hi Arne,

for a little [Donate](https://www.paypal.me/dirkpersky/29.99) sure i can do it. If you are interested send me a mail, with alle access information ftp, backend, doccheck and the doccheck demo account.

greetings
Dirk

**Comment by w3creative** [comment]
Hi Dirk
Of course! Donation: check. Page with docCheck: https://www.schwabepharma.be/professionelen/ The target url is already linked, but you are allowed to create a new link… ;)
Data: - Site frontend: www.schwabepharma.be Access: U: schwabe_be P: schwabeBE - Site backend: www.schwabepharma.be/typo3 Backend user: administration / nE0FNOmEFFXw1xMvG5Pt
- DocCheck cream login: muriel7 / thibault Frontend user Typo3: user / user
FTP Host: 185.56.145.201 User: wwwschwabepharma Pass: Schwabe/01
Could you please inform me what was wrong?
Many thanks Arne
[https://htmlsig.com/t/000001BW9729]

Arne Dondeyne / Zaakvoerder
arne@w3-creative.be [arne@w3-creative.be] / +32495374331

w3-creative
www.w3-creative.be [http://www.w3-creative.be]

[https://htmlsig.com/t/000001BYBH3Y]

Success is going from failure to failure without losing enthusiasm.


On do, jul. 26, 2018 at 17:11, Dirk Persky <notifications@github.com> wrote:
Hi Arne,

for a little Donate [https://www.paypal.me/dirkpersky/29.99] sure i can do it. If you are interested send me a mail, with alle access information ftp, backend, doccheck and the doccheck demo account.

greetings
Dirk

**Comment by DirkPersky** [comment]
you shoud change you post, the Information are avalible on GitHub *ggg*

**Comment by w3creative** [comment]
Thanks! Done... 
You still have the info? :)

**Comment by DirkPersky** [comment]
yes ;)

**Comment by DirkPersky** [comment]
He Arne ;( 

i watched the last 2:30 hours for you problem, but it is not a problem about the doccheck. There all works  fine.
The api handing is fine, request, responce...
It sets all the Cookie Variable correct for the User.
Attached the Login correct, no problem from that side.

It seems it is more a Problem about TYPO3, another Extension or the Medienpalast Plugins.
When i activate the default fe_login it dosen't work too.

For me it looked liked the TYPO3-Core user login check is broked by something.
The only modules i cant disabled becouse of it requirements was the "mediapalast"

**Comment by DirkPersky** [comment]
It was just simply, next time i put the backend in my default language xD

Page Config > Toegang > Aanmeldgedrag > **Aanmelden inschakelen**
^^ was on "utschakelen"

Pagge Config > Access > Login Behaviour > **Enable login**
^^ was on "disable login"

**Comment by w3creative** [comment]
Hi Dirk
Many thanks for your input! This is awesome. Have a good day!


On do, jul. 26, 2018 at 22:54, Dirk Persky <notifications@github.com> wrote:
It was just simply, next time i put the backend in my default language xD

Page Config > Toegang > Aanmeldgedrag > Aanmelden inschakelen
^^ was on "utschakelen"

Pagge Config > Access > Login Behaviour > Enable login
^^ was on "disable login"

**Comment by w3creative** [comment]
Hi
I have also made a docCheck login for the French version. Target: https://www.schwabepharma.be/fr/professionelles/lexpert-en-phytotherapie/. If I log in via https://www.schwabepharma.be/fr/professionelles/ I get an error message. I first log on via Dutch login, then I see the page.
Do I need to configure something for this? Arne
[https://htmlsig.com/t/000001BW9729]

Arne Dondeyne / Zaakvoerder
arne@w3-creative.be [arne@w3-creative.be] / +32495374331

w3-creative
www.w3-creative.be [http://www.w3-creative.be]

[https://htmlsig.com/t/000001BYBH3Y]

Success is going from failure to failure without losing enthusiasm.


On do, jul. 26, 2018 at 22:54, Dirk Persky <notifications@github.com> wrote:
It was just simply, next time i put the backend in my default language xD

Page Config > Toegang > Aanmeldgedrag > Aanmelden inschakelen
^^ was on "utschakelen"

Pagge Config > Access > Login Behaviour > Enable login
^^ was on "disable login"
