### ISSUE TITLE
Fe-User not loggin in on T3, 7.6.18, but DC-Windows shows User as logged in...

### ISSUE THREAD

**Issue by MalathDaThon** [antwerpes/ap_docchecklogin#8]
Hi :) 

I got some problem with Version 1.1.0 on Typo3 7.6.18

I already used thix extension on various typ03 6.x installations and i think i know how to set it up correctly.

Tried to de-install and install it again, step by step following the documentation but user isn´t logged in correctly.
The doccheck window shows the user as logged in, but typo isn´t doing anything.
Content won´t show up.

tried with PHP set to 5.5, 5.6 & 7.0
even tried with compatibility 6 installed - no effort.

No errors in logfiles or debug settings.

Do you have any idea or sugesstion?

Thx and kind regards, Jo

**Comment by DirkPersky** [comment]
I had the Same problem.
There was 2 IF-Conditions which handelt the Type not Correctly.

In my Pull Request you can see what you need to change, or use that version.
I testet my Version on PHP 7.1 + Typo3 8.7.7

Greeting
Dirk
